/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oop2.lms.frame;

import com.oop2.lms.components.DatePicker;
import com.oop2.lms.db.DbHelper;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author morax
 */
public class AddBorrowingFrame extends javax.swing.JFrame {

    private final DbHelper dbHelper;

    /**
     * Creates new form AddUserFrame
     */
    public AddBorrowingFrame() {
        initComponents();
        getContentPane().setBackground(new Color(32, 36, 51));
        dbHelper = new DbHelper();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        dueDateTxt.setText(sdf.format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userIdTxt = new com.oop2.lms.components.TextField();
        jLabel3 = new javax.swing.JLabel();
        addBookBtn = new com.oop2.lms.components.Button();
        jButton1 = new javax.swing.JButton();
        bookIdTxt = new com.oop2.lms.components.TextField();
        jLabel4 = new javax.swing.JLabel();
        dueDateTxt = new com.oop2.lms.components.TextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(32, 36, 51));
        setMaximumSize(new java.awt.Dimension(500, 700));
        setMinimumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(500, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Add Borrowing Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));
        getContentPane().add(userIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 360, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("User ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        addBookBtn.setText("Add Borrowing");
        addBookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBookBtnMouseClicked(evt);
            }
        });
        getContentPane().add(addBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 360, 50));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 100, 40));
        getContentPane().add(bookIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 360, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Book ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        dueDateTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dueDateTxtMouseClicked(evt);
            }
        });
        getContentPane().add(dueDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 360, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Due Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookBtnMouseClicked
        // TODO add your handling code here:
        int userId = Integer.parseInt(userIdTxt.getText());
        int bookId = Integer.parseInt(bookIdTxt.getText());
        ResultSet rs = dbHelper.getBook(bookId);
        try {
            if (rs != null && rs.next()) {
                int stocks = rs.getInt("stocks");
                if(stocks <= 0){
                    JOptionPane.showMessageDialog(this, "No stock available for this book id", "Error stock availability", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateUserFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dueDate = dueDateTxt.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            dbHelper.addBorrowing(userId, bookId, sdf.parse(dueDate));
        } catch (ParseException ex) {
            Logger.getLogger(AddBorrowingFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        DashboardFrame dashboardFrame = new DashboardFrame();
        dashboardFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_addBookBtnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        DashboardFrame dashboardFrame = new DashboardFrame();
        dashboardFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void dueDateTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dueDateTxtMouseClicked
        // TODO add your handling code here:
        DatePicker datePicker = new DatePicker();
        datePicker.setLocationRelativeTo(this);
        datePicker.setVisible(true);
        String pickedDate = datePicker.setPickedDate();
        if (pickedDate != null) {
            dueDateTxt.setText(pickedDate);
        }
    }//GEN-LAST:event_dueDateTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBorrowingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBorrowingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBorrowingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBorrowingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBorrowingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.oop2.lms.components.Button addBookBtn;
    private com.oop2.lms.components.TextField bookIdTxt;
    private com.oop2.lms.components.TextField dueDateTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.oop2.lms.components.TextField userIdTxt;
    // End of variables declaration//GEN-END:variables
}
