/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oop2.lms.frame;

import com.oop2.lms.db.DbHelper;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PULVERA
 */
public class UpdateBookFrame extends javax.swing.JFrame {

    private final DbHelper dbHelper;
    /**
     * Creates new form AddUserFrame
     */
    public UpdateBookFrame() {
        initComponents();
        getContentPane().setBackground(new Color(32, 36, 51));
        dbHelper = new DbHelper();
    }
    
    public void loadBook(int bookId) {
        ResultSet rs = dbHelper.getBook(bookId);
        try {
            if (rs != null && rs.next()) {
                int id = rs.getInt("book_id");
                String title = rs.getString("title");
                String author = rs.getString("author");
                String category = rs.getString("category");
                int stocks = rs.getInt("stocks");
                bookIdLbl.setText(String.valueOf(id));
                titleTxt.setText(title);
                authorTxt.setText(author);
                categoryTxt.setText(category);
                stocksTxt.setText(String.valueOf(stocks));
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateUserFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        titleTxt = new com.oop2.lms.components.TextField();
        jLabel3 = new javax.swing.JLabel();
        updateBookBtn = new com.oop2.lms.components.Button();
        jButton1 = new javax.swing.JButton();
        authorTxt = new com.oop2.lms.components.TextField();
        jLabel4 = new javax.swing.JLabel();
        categoryTxt = new com.oop2.lms.components.TextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bookIdLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        categoryTxt1 = new com.oop2.lms.components.TextField();
        jLabel7 = new javax.swing.JLabel();
        stocksTxt = new com.oop2.lms.components.TextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(32, 36, 51));
        setMinimumSize(new java.awt.Dimension(500, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Update Book Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));
        getContentPane().add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 360, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Title");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        updateBookBtn.setText("Update Book");
        updateBookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBookBtnMouseClicked(evt);
            }
        });
        getContentPane().add(updateBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 360, 50));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 100, 40));
        getContentPane().add(authorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 360, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Author");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));
        getContentPane().add(categoryTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 360, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Category");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel2.setText("Book ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        bookIdLbl.setText("0");
        getContentPane().add(bookIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Category");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));
        getContentPane().add(categoryTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 360, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Category");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));
        getContentPane().add(stocksTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 360, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Stocks");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateBookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBookBtnMouseClicked
        // TODO add your handling code here:
        String title = titleTxt.getText();
        String author = authorTxt.getText();
        String category = categoryTxt.getText();
        int stocks = Integer.parseInt(stocksTxt.getText());
        dbHelper.updateBook(Integer.parseInt(bookIdLbl.getText()), title, author, category, stocks);
        DashboardFrame dashboardFrame = new DashboardFrame();
        dashboardFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_updateBookBtnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        DashboardFrame dashboardFrame = new DashboardFrame();
        dashboardFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateBookFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.oop2.lms.components.TextField authorTxt;
    private javax.swing.JLabel bookIdLbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.oop2.lms.components.TextField categoryTxt;
    private com.oop2.lms.components.TextField categoryTxt1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.oop2.lms.components.TextField stocksTxt;
    private com.oop2.lms.components.TextField titleTxt;
    private com.oop2.lms.components.Button updateBookBtn;
    // End of variables declaration//GEN-END:variables
}
