/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.oop2.lms.panel;

import com.oop2.lms.db.DbHelper;

/**
 *
 * @author morax
 */
public class AddUser extends javax.swing.JPanel {

    private final DbHelper dbHelper;

    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
        dbHelper = new DbHelper();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleRb = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        usernameTxt = new com.oop2.lms.components.TextField();
        jLabel2 = new javax.swing.JLabel();
        passwordTxt = new com.oop2.lms.components.PasswordField();
        jLabel3 = new javax.swing.JLabel();
        librarianRb = new javax.swing.JRadioButton();
        userRb = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        addUserBtn = new com.oop2.lms.components.Button();

        setBackground(new java.awt.Color(32, 36, 51));
        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add User Form");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));
        add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 360, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Select a role:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));
        add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 360, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Username");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        roleRb.add(librarianRb);
        librarianRb.setText("Librarian");
        add(librarianRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        roleRb.add(userRb);
        userRb.setText("User");
        add(userRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        addUserBtn.setText("Add User");
        addUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserBtnMouseClicked(evt);
            }
        });
        add(addUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 360, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void addUserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserBtnMouseClicked
        // TODO add your handling code here:
        String username = usernameTxt.getText();
        char[] passwordChars = passwordTxt.getPassword();
        String password = new String(passwordChars);
        String role = "";
        if (librarianRb.isSelected()) {
            role = "librarian";
        } else if (userRb.isSelected()) {
            role = "user";
        }
        dbHelper.addUser(username, password, role);
    }//GEN-LAST:event_addUserBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.oop2.lms.components.Button addUserBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton librarianRb;
    private com.oop2.lms.components.PasswordField passwordTxt;
    private javax.swing.ButtonGroup roleRb;
    private javax.swing.JRadioButton userRb;
    private com.oop2.lms.components.TextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
